# Generated by Django 2.2 on 2021-10-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('adminname', models.CharField(max_length=32)),
                ('adminpassword', models.CharField(max_length=32)),
                ('adminsex', models.CharField(max_length=32)),
            ],
        ),
    ]
